import sbt._
import Keys._
import scala.util.Using
import scala.io.Source

/** Auto plugin to generate BaseSchema object containing property name constants from a base JSON schema. */
object BaseSchemaGeneratorPlugin extends AutoPlugin {
  object autoImport {
    val generateBaseSchemaConstants = taskKey[Seq[File]]("Generate BaseSchema property name constants from base schema JSON")
    val baseSchemaJsonFile          = settingKey[File]("Location of the base JSON schema file (must contain top-level 'properties')")
    val baseSchemaObjectPackage     = settingKey[String]("Scala package for generated BaseSchema object")
    val baseSchemaObjectName        = settingKey[String]("Name of generated Scala object containing constants")
  }
  import autoImport._

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Setting[_]] = {
    val alias = addCommandAlias("genBaseSchema", "compile")
    Seq(
      baseSchemaJsonFile      := (Compile / resourceDirectory).value / "organisationBase.json",
      baseSchemaObjectPackage := "validation.generated",
      baseSchemaObjectName    := "BaseSchema",
      Compile / sourceGenerators += generateBaseSchemaConstants.taskValue,
      generateBaseSchemaConstants := {
        val log        = streams.value.log
        val schemaFile = baseSchemaJsonFile.value
        val outDir     = (Compile / sourceManaged).value / "generated"
        val objectName = baseSchemaObjectName.value
        val pkg        = baseSchemaObjectPackage.value

        log.info("[BaseSchemaGenerator] Task started")
        log.info("[BaseSchemaGenerator] schemaFile = " + schemaFile)
        log.info("[BaseSchemaGenerator] outDir = " + outDir)

        if (!schemaFile.exists()) {
          log.warn("[BaseSchemaGenerator] Schema file not found: " + schemaFile)
          Seq.empty
        } else {
          log.info("[BaseSchemaGenerator] Generating constants from: " + schemaFile.getName)
          import ujson._
          import scala.util.Try

          val jsonStrTry = Try(Using(Source.fromFile(schemaFile)(scala.io.Codec.UTF8))(_.mkString).get)
          val parsedTry  = jsonStrTry.flatMap(str => Try(ujson.read(str)))

          parsedTry.fold(
            { err =>
              log.error("[BaseSchemaGenerator] Failed to parse JSON: " + err.getMessage)
              Seq.empty
            },
            { parsed =>
              val propNames: Seq[String] = parsed.obj.get("properties") match {
                case Some(obj: ujson.Obj) => obj.value.keys.toSeq.sorted
                case _ =>
                  log.warn("[BaseSchemaGenerator] No 'properties' object found in base schema. Nothing generated.")
                  Seq.empty
              }

              log.info("[BaseSchemaGenerator] Extracted " + propNames.size + " raw property names")

              if (propNames.isEmpty) {
                log.warn("[BaseSchemaGenerator] No property names extracted. Skipping generation.")
                Seq.empty
              } else {
                // Scala reserved keywords that need backticks or alteration
                val scalaKeywords = Set(
                  "abstract","case","catch","class","def","do","else","enum","export","extends","false","final","finally",
                  "for","given","if","implicit","import","lazy","match","new","null","object","override","package","private",
                  "protected","return","sealed","super","then","this","throw","trait","true","try","type","val","var","while",
                  "with","yield"
                )

                val used = scala.collection.mutable.HashSet[String]()
                def unique(name: String): String = {
                  if (!used.contains(name)) { used += name; name }
                  else {
                    var i = 2
                    var candidate = name + "_" + i
                    while (used.contains(candidate)) { i += 1; candidate = name + "_" + i }
                    used += candidate
                    candidate
                  }
                }

                val constants = propNames.map { name =>
                  val prefixed = if (name.nonEmpty && name.charAt(0).isDigit) "_" + name else name
                  val sanitized = prefixed
                    .replaceAll("[^A-Za-z0-9_]", "_")
                    .replaceAll("_+", "_")
                    .stripSuffix("_")
                    .stripPrefix("_") match {
                      case "" => "_"
                      case other => other
                    }
                  val keywordSafe = if (scalaKeywords.contains(sanitized)) sanitized + "_" else sanitized
                  val finalIdent  = unique(keywordSafe)
                  "  final val " + finalIdent + ": String = \"" + name + "\""
                }.mkString("\n")

                val code =
                  """|// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
                     |// Generated by BaseSchemaGeneratorPlugin from: %s
                     |package %s
                     |
                     |/**
                     | * Constants representing property names from the base schema file.
                     | * Total properties: %d
                     | */
                     |object %s {
                     |%s
                     |}
                     |""".stripMargin.format(schemaFile.getName, pkg, propNames.size, objectName, constants)

                outDir.mkdirs()
                val outFile = outDir / (objectName + ".scala")
                IO.write(outFile, code)
                log.info("[BaseSchemaGenerator] Wrote " + outFile.getAbsolutePath + s" (${propNames.size} constants)")
                Seq(outFile)
              }
            }
          )
        }
      }
    ) ++ alias
  }
}
