import sbt._
import Keys._
import scala.io.Source
import scala.util.Using

/** Auto plugin to generate constants for each distinct domain value found in config.json (configItems[].domainKeys[].domain).
  * Produces a Scala object with one constant per domain.
  */
object DomainKeysGeneratorPlugin extends AutoPlugin {
  object autoImport {
    val generateConfigDomainsConstants = taskKey[Seq[File]]("Generate constants for domain entries in config.json")
    val configJsonFile                 = settingKey[File]("Path to config.json containing configItems")
    val configDomainsObjectPackage     = settingKey[String]("Package name for generated domains object")
    val configDomainsObjectName        = settingKey[String]("Object name for generated domains constants")
  }
  import autoImport._

  // Move case classes and upickle ReadWriter implicits to module-level to avoid SI-7567
  import upickle.default._
  private case class DomainKey(domain: String, domainKey: String)
  private case class ConfigItem(key: String, domainKeys: Option[List[DomainKey]])
  private case class Config(configItems: List[ConfigItem])
  private implicit val domainKeyRW: ReadWriter[DomainKey]   = macroRW
  private implicit val configItemRW: ReadWriter[ConfigItem] = macroRW
  private implicit val configRW: ReadWriter[Config]         = macroRW

  override def trigger: PluginTrigger = allRequirements

  override def projectSettings: Seq[Setting[_]] = Seq(
    configJsonFile             := (Compile / resourceDirectory).value / "config.json",
    configDomainsObjectPackage := "validation.generated",
    configDomainsObjectName    := "ConfigDomains",
    Compile / sourceGenerators += generateConfigDomainsConstants.taskValue,
    generateConfigDomainsConstants := {
      val log        = streams.value.log
      val file       = configJsonFile.value
      val outDir     = (Compile / sourceManaged).value / "generated"
      val objectName = configDomainsObjectName.value
      val pkg        = configDomainsObjectPackage.value

      if (!file.exists()) {
        log.warn("[DomainKeysGenerator] config.json not found: " + file)
        Seq.empty
      } else {
        log.info("[DomainKeysGenerator] Parsing (typed): " + file.getName)
        val jsonStr = Using(Source.fromFile(file)(scala.io.Codec.UTF8))(_.mkString).get

        val parsed = try read[Config](jsonStr) catch {
          case e: Throwable =>
            log.error("[DomainKeysGenerator] Failed to decode config.json: " + e.getMessage)
            return Seq.empty
        }

        val domains: Seq[String] = parsed.configItems.flatMap(_.domainKeys.getOrElse(Nil).map(_.domain)).map(_.trim).filter(_.nonEmpty).distinct.sorted

        if (domains.isEmpty) {
          log.warn("[DomainKeysGenerator] No domains discovered. Skipping generation.")
          Seq.empty
        } else {
          // Generate sanitized identifiers for case objects
          val domainDefs = domains.map { d =>
            val prefixed = if (d.nonEmpty && d.charAt(0).isDigit) "_" + d else d
            val safe = prefixed
              .replaceAll("[^A-Za-z0-9_]", "_")
              .replaceAll("_+", "_")
              .stripSuffix("_")
            (safe, d)
          }

          val enumCases = domainDefs.map { case (ident, raw) =>
            s"""    case $ident extends Domain("$raw")"""
          }.mkString("\n")

          val code =
            s"""|// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
                |// Generated by DomainKeysGeneratorPlugin (typed parsing) from: ${file.getName}
                |package $pkg
                |
                |/**
                | * Domain enumeration extracted from config.json (configItems[].domainKeys[].domain)
                | * Total domains: ${domains.size}
                | *
                | * Use Domain.values to get all values, Domain.valueOf("name") for case-insensitive lookup,
                | * or Domain.fromString("original") for runtime lookup by original domain string.
                | */
                |object $objectName:
                |  enum Domain(val value: String):
                |$enumCases
                |
                |  object Domain:
                |    def fromString(s: String): Option[Domain] = values.find(_.value == s)
                |""".stripMargin

          outDir.mkdirs()
          val outFile = outDir / (objectName + ".scala")
          IO.write(outFile, code)
          log.info("[DomainKeysGenerator] Generated " + outFile.getAbsolutePath + s" (${domains.size} domain enums)")
          Seq(outFile)
        }
      }
    }
  )
}
