on:
  pull_request:
    types:
      - closed 

jobs:
  get_files:
    name: merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Modified_files
        id: set-env
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              firstCommit="${{ github.event.pull_request.base.sha }}"
              lastCommit="${{ github.event.pull_request.head.sha }}"
                 
            if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
              echo "Error: firstCommit or lastCommit is empty."
              exit 1
            fi
        
            changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
            if echo "$changedFiles" | grep -q "package.json"; then
               echo "ts-only=true" >> $GITHUB_OUTPUT
            else
              echo "ts-only=false" >> $GITHUB_OUTPUT
            fi
          else
             echo "ts-only=false" >> $GITHUB_OUTPUT
          fi  
        
      - name: print
        run: |
          echo "TESTING_ENVIRONMENT=${{ steps.set-env.outputs.ts-only }}"
          echo "Finished hopefully working"
