on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  get_files:
    name: run_on_pr_or_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Modified files
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            firstCommit="${{ github.event.before }}"
            lastCommit="${{ github.event.after }}"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            firstCommit="${{ github.event.pull_request.base.sha }}"
            lastCommit="${{ github.event.pull_request.head.sha }}"
          fi
      
          echo "First Commit: $firstCommit"
          echo "Last Commit: $lastCommit"
      
          if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
            echo "Error: firstCommit or lastCommit is empty."
            exit 1
          fi
      
          changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
          echo "Changed files:"
          echo "$changedFiles"
          if echo "$changedFiles" | grep -q "aws.yml"; then
          echo "The file 'aws.yml' has been modified."
          else
            echo "The file 'aws.yml' has not been modified."
          fi
