on:
  pull_request:
    types:
      - closed 

jobs:
  get_files:
    name: merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Modified_files
        id: set-env
        run: |
          echo "Checking"
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            
            firstCommit="${{ github.event.pull_request.base.sha }}"
            lastCommit="${{ github.event.pull_request.head.sha }}"
                 
            echo "First Commits: $firstCommit"
            echo "Last Commit: $lastCommit"
        
            if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
              echo "Error: firstCommit or lastCommit is empty."
              exit 1
            fi
        
            changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
            echo "Changed files:"
            echo "$changedFiles"
            if echo "$changedFiles" | grep -q "aws.yml"; then
              echo "TESTING_ENVIRONMENT=1"
              echo "ts-only=true" >> $GITHUB_OUTPUT
            else
              echo "TESTING_ENVIRONMENT=2"
              echo "ts-only=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "TESTING_ENVIRONMENT=3"
            echo "ts-only=false" >> $GITHUB_OUTPUT
          fi  
         
      - name: print
        run: |
          echo "TESTING_ENVIRONMENT=${{ steps.set-env.outputs.ts-only }}"
          echo "Finished working"
