on:
  pull_request:
    types:
      - closed 

jobs:
  get_files:
    name: merged files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Modified files
        id: set-ts-only
        run: |
          echo "Checking"
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            
            firstCommit="${{ github.event.pull_request.base.sha }}"
            lastCommit="${{ github.event.pull_request.head.sha }}"
                 
            echo "First Commit: $firstCommit"
            echo "Last Commit: $lastCommit"
        
            if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
              echo "Error: firstCommit or lastCommit is empty."
              exit 1
            fi
        
            changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
            echo "Changed files:"
            echo "$changedFiles"
            if echo "$changedFiles" | grep -q "aws.yml"; then
              echo "TESTING_ENVIRONMENT=1" >> $GITHUB_ENV
              echo "ts-only=true" 
              echo "ts-only=true" >> $GITHUB_ENV
            else
              echo "ts-only=false"
              echo "TESTING_ENVIRONMENT=2" >> $GITHUB_ENV
              echo "ts-only=false" >> $GITHUB_ENV
            fi
          else
            echo "TESTING_ENVIRONMENT=3" >> $GITHUB_ENV
            echo "ts-only=false" >> $GITHUB_ENV
          fi  
           echo "working ${{ env.TESTING_ENVIRONMENT }}"
  print: 
    needs: get_files
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "yo ${{ steps.set-ts-only.outputs.ts-only }}"
          echo "${{ env.ts-only }}"
