on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  get_files:
    name: run_on_pr_or_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Modified file
        run: |
          echo "Checking"
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            
            firstCommit="${{ github.event.pull_request.base.sha }}"
            lastCommit="${{ github.event.pull_request.head.sha }}"
                 
            echo "First Commit: $firstCommit"
            echo "Last Commit: $lastCommit"
        
            if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
              echo "Error: firstCommit or lastCommit is empty."
              exit 1
            fi
        
            changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
            echo "Changed files:"
            echo "$changedFiles"
            if echo "$changedFiles" | grep -q "aws.yml"; then
              echo "ts-only=true" >> $GITHUB_ENV
            else
              echo "ts-only=false" >> $GITHUB_ENV
            fi
          else
            echo "ts-only=false" >> $GITHUB_ENV
          fi  
          
  print: 
    needs: get_files
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "${{ env.ts-only }}"
