name: Tag if there are only ts changes
on:
  pull_request:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Check ts-only
        id: package-json-changed
        run: |
          firstCommit="${{ github.event.pull_request.base.sha }}"
          lastCommit="${{ github.event.pull_request.head.sha }}"
          
          if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
            echo "Error: firstCommit or lastCommit is empty."
            exit 1
          fi
          
          changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
          if echo "$changedFiles" | grep -q "resources/organisationBase.json"; then
             echo "package-json-modified=true" >> $GITHUB_OUTPUT
          else
            echo "package-json-modified=false" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.package-json-changed.outputs.package-json-modified == 'true' }}
        run: echo "Modified ${{ steps.package-json-changed.outputs.package-json-modified }}" 
      - if: ${{ steps.package-json-changed.outputs.package-json-modified == 'false' }}
        run: echo "Modified ${{ steps.package-json-changed.outputs.package-json-modified }}" 
      
